### ISSUE TITLE
Level 0 DFD

### ISSUE THREAD

**Issue by ShamusBoulianne** [japser36/COSC-499-Pace-A#17]
Create an overview of the system architecture in the form of a level 0 data flow diagram (DFD) as well as an accompanying description of the diagram.

This task counts towards the completion of issue #15

**Comment by japser36** [comment]
I created a level 0 DFD for the presentation, found here: https://lucid.app/invitations/accept/442376e1-ca61-4275-9f90-2bfa05d293e2
Let's add it to the design document
