### ISSUE TITLE
Identify Testing Methods

### ISSUE THREAD

**Issue by ShamusBoulianne** [japser36/COSC-499-Pace-A#22]
Here is the task as described on the course website:
An explanation of how you will test the developed features of your system (in accordance with the tech stack chosen) as well as the method you will adopt to ensure continuous integration. Don't just use a technical term to describe the method; write a few sentences to explain the tools and techniques that will be involved. Read up on regression testing, and develop a feasible plan that ensures when new code is added to your project that your project didn't break anything that was working before.

**Comment by zil93** [comment]
For test strategy this link might be useful: https://github.com/brandongk-ubco/gitstats/blob/develop/docs/technical/testing.md

**Comment by ShamusBoulianne** [comment]
> For test strategy this link might be useful: https://github.com/brandongk-ubco/gitstats/blob/develop/docs/technical/testing.md

Thank you. This link has proven to be very helpful.
